DRCTS/Controllers/DRCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DRCTS.Models;
using System.Web.Security;
using M.Radwan.DevMagicFake.FakeRepositories;
using Faker;
using PublicHoliday;
using EmailValidation;
using Mail4Net;
using System.Net.Mail;
using NLog;


namespace DRCTS.Controllers
{
    public class DRCController : Controller
    {
        Logger logger = LogManager.GetCurrentClassLogger();
        IdrctsRepository drcRepo;
        public DRCController() 
            : this(new drctsRepository())
        {

        }
        public DRCController(IdrctsRepository repo)
        {
            drcRepo = repo;
        }
        //drctsRepository drcRepo = new drctsRepository();
       // DRCTSClassesDataContext dc = new DRCTSClassesDataContext();
        // GET: DRC
        [Authorize, HandleError]
        public ActionResult Index()
        {
            ViewBag.User = User.Identity.Name;
            List<CustomSearchResult> nRes = drcRepo.rSearch();
            //IQueryable<tDRCRequest> query1 = query;
            IQueryable<CustomSearchResult> query1 = nRes.AsQueryable();
            //List<tDRCRequest> sResults = new List<tDRCRequest>();
            //var query = dc.tDRCRequests;
            //IQueryable<tDRCRequest> query1 = query;
            // query1 = query1.Where(h => h.OC == null); //.Where(e => e.deleted.Equals(false));
            IQueryable<CustomSearchResult> queryOpen = query1.Where(h => h.DRCStatus == "Open").Where(d => d.deleted == false);
            IQueryable<CustomSearchResult> queryNew = query1.Where(h => h.DRCStatus == "New").Where(d => d.deleted == false);
            IQueryable<CustomSearchResult> queryFull = query1.Where(h => h.DRCStatus == "Fulfilled").Where(d => d.deleted == false);
            IQueryable<CustomSearchResult> queryOther = query1.Where(h => h.DRCStatus == "Other").Where(d => d.deleted == false);
            IQueryable<CustomSearchResult> queryAss = query1.Where(h => h.AnalystAssigned == null).Where(d => d.deleted == false);
            ViewBag.open = queryOpen.ToList().Count;
            ViewBag.full = queryFull.ToList().Count;
            ViewBag.other = queryOther.ToList().Count;
            ViewBag.newR = queryNew.ToList().Count;
            ViewBag.testr = "sh!t";
            //TempData["Rm"] = "testing";
            return View();
        }
        public ActionResult Index2()
        {
            try
            {
                int x = 0;
                int y = 5;
                int z = y / x;
            }
            catch (Exception ex)
            {
                logger.Error(ex,"Error occured in Home controller Index Action");

            }
            return View();
        }
        public ActionResult Index3()
        {
            return View();
        }
        public ActionResult Index4()
        {
            return View();
        }
        public ActionResult Index1()
        {
            return View();
        }

        [Authorize]
        public PartialViewResult UserTasks()
        {
            List<OpenUserRequestsResult> oup = new List<OpenUserRequestsResult>();
            oup = drcRepo.DRCOpenAssigned(User.Identity.Name);
            return PartialView(oup);
        }
        public PartialViewResult Service_Report(string year)
        {
            List<ServiceReportResult> svr = new List<ServiceReportResult>();
            svr = drcRepo.rptService(year);
            return PartialView(svr);
        }
        public PartialViewResult Disability_Report(string year)
        {
            List<DisabilityReportResult> dbr = new List<DisabilityReportResult>();
            dbr = drcRepo.rptDisability(year);
            return PartialView(dbr);
        }
        public PartialViewResult Status_Report(string year)
        {
            List<StatusReportResult> srr = new List<StatusReportResult>();
            srr = drcRepo.rptStatus(year);
            return PartialView(srr);
        }
        public PartialViewResult MD715Report(string year)
        {
            List<MD715ReportResult> md = new List<MD715ReportResult>();
            md = drcRepo.rptMD715(year);
            return PartialView(md);
        }
        public PartialViewResult ReqMD715Report(string year)
        {
            List<ReqMD715ReportResult> md = new List<ReqMD715ReportResult>();
            md = drcRepo.reqrptMD715(year);
            return PartialView(md);
        }
        public PartialViewResult RAbyUser(string year)
        {
            List<RAAnylistResult> byRA = new List<RAAnylistResult>();
            byRA = drcRepo.rptRAAnylist(year);
            return PartialView(byRA);
        }
        public PartialViewResult CustomColumns()
        {
           
            var list = new List<CheckModel>
            {
                 new CheckModel{Id = 1, Name = "OA", Checked = true},
                 new CheckModel{Id = 2, Name = "Employee Last Name", Checked = true},
                 new CheckModel{Id = 3, Name = "Employee First Name", Checked = true},
                 new CheckModel{Id = 4, Name = "Position", Checked = false},
                 new CheckModel{Id = 5, Name = "Grade", Checked = false},
                 new CheckModel{Id = 6, Name = "Employee Phone", Checked = false},
                 new CheckModel{Id = 7, Name = "Employee Email", Checked = false},
                 new CheckModel{Id = 8, Name = "Disability", Checked = true},
                 new CheckModel{Id = 9, Name = "Supervisor Last Name", Checked = false},
                 new CheckModel{Id = 10, Name = "Supervisor First Name", Checked = false},
                 new CheckModel{Id = 11, Name = "Supervisor Email", Checked = false},
                 new CheckModel{Id = 12, Name = "Supervisor Phone", Checked = false},
                 new CheckModel{Id = 13, Name = "Description", Checked = true},
                 new CheckModel{Id = 14, Name = "Date Request Received", Checked = true},
                 new CheckModel{Id = 15, Name = "COWA Date", Checked = false},
                 new CheckModel{Id = 16, Name = "Quarter Received", Checked = false},
                 new CheckModel{Id = 17, Name = "Date Completed", Checked = false},
                 new CheckModel{Id = 18, Name = "Date Fulfilled", Checked = false},
                 new CheckModel{Id = 19, Name = "DRC Request Type", Checked = false},
                 new CheckModel{Id = 20, Name = "DRC Status", Checked = true},
                 new CheckModel{Id = 21, Name = "OC", Checked = false},
                 new CheckModel{Id = 22, Name = "Source", Checked = false},
                 new CheckModel{Id = 23, Name = "Requested MD715", Checked = false},
                 new CheckModel{Id = 24, Name = "MD-715 Category After RA process", Checked = false},
                 new CheckModel{Id = 25, Name = "Analyst Assigned", Checked = true},
                 new CheckModel{Id = 26, Name = "Describe Provided Accommodation", Checked = false},
                 new CheckModel{Id = 27, Name = "Time Frame today", Checked = false},
                 new CheckModel{Id = 28, Name = "Notes", Checked = false},
                 new CheckModel{Id = 29, Name = "Comments", Checked = false},
                 new CheckModel{Id = 30, Name = "Created By", Checked = false},
                 new CheckModel{Id = 31, Name = "Purchasing", Checked = false},
                new CheckModel{Id = 32, Name = "PR Number", Checked = false},
                new CheckModel{Id = 33, Name = "PR Amount", Checked = false},
                 new CheckModel{Id = 34, Name = "Updated By", Checked = false},
                 new CheckModel{Id = 35, Name = "Created Date", Checked = false},
                 new CheckModel{Id = 36, Name = "Updated Date", Checked = false},


            };
            return PartialView(list);
        }
        public ActionResult All_Open_Requests()
        {
            //List<CustomSearchResult> opRes = new List<CustomSearchResult>();
           // var query = dc.tDRCRequests;
             

            //List<ResultsResult> nRes = drcRepo.rSearch();
            //IQueryable<tDRCRequest> query1 = drcRepo.allReq().AsQueryable();
           IQueryable<ResultsResult> query1 = drcRepo.allSearch().AsQueryable();
            List<ResultsResult> sResults = new List<ResultsResult>();
            //var query = dc.tDRCRequests;
            //IQueryable<tDRCRequest> query1 = query;
            // query1 = query1.Where(h => h.OC == null); //.Where(e => e.deleted.Equals(false));
            query1 = query1.Where(h => h.DRCStatus == "Open").Where(d => d.deleted == false).OrderByDescending(c=> c.CreatedDate);
            //query1 = query1.Where(c => c.SupervisorLastName.Contains("Cummings"));
            //opRes = query1.ToList();
            sResults = query1.ToList();
            
            ViewBag.Header = "Open Requests";
            //return View();
            return View("searchresults", sResults);

        }
        public ActionResult All_Fulfilled_Requests()
        {
            //List<CustomSearchResult> opRes = new List<CustomSearchResult>();
            // var query = dc.tDRCRequests;


            //List<ResultsResult> nRes = drcRepo.rSearch();
            //IQueryable<tDRCRequest> query1 = drcRepo.allReq().AsQueryable();
            IQueryable<ResultsResult> query1 = drcRepo.allSearch().AsQueryable();
            List<ResultsResult> sResults = new List<ResultsResult>();
            //var query = dc.tDRCRequests;
            //IQueryable<tDRCRequest> query1 = query;
            // query1 = query1.Where(h => h.OC == null); //.Where(e => e.deleted.Equals(false));
            query1 = query1.Where(h => h.DRCStatus == "Fulfilled").Where(h => h.deleted == false).OrderByDescending(c => c.CreatedDate);
            //query1 = query1.Where(c => c.SupervisorLastName.Contains("Cummings"));
            //opRes = query1.ToList();
            sResults = query1.ToList();

DRCTS/Controllers/JSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SessionTimeout.Controllers
{
    public class JSController : Controller
    {
        // GET: JS
        public ActionResult Index()
        {
            return new EmptyResult();
        }
    }
}

DRCTS/Controllers/RolesAdminController.cs
using IdentitySample.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Collections.Generic;

namespace IdentitySample.Controllers
{
    [Authorize(Roles = "DRCAdmin")]
    public class RolesAdminController : Controller
    {
        public RolesAdminController()
        {
        }

        public RolesAdminController(ApplicationUserManager userManager,
            ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Roles/
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        //
        // GET: /Roles/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            // Get the list of Users in this Role
            var users = new List<ApplicationUser>();

            // Get the list of Users in this Role
            foreach (var user in UserManager.Users.ToList())
            {
                if (await UserManager.IsInRoleAsync(user.Id, role.Name))
                {
                    users.Add(user);
                }
            }

            ViewBag.Users = users;
            ViewBag.UserCount = users.Count();
            return View(role);
        }

        //
        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole(roleViewModel.Name);
                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    ModelState.AddModelError("", roleresult.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Edit/Admin
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            RoleViewModel roleModel = new RoleViewModel { Id = role.Id, Name = role.Name };
            return View(roleModel);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]

        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Name,Id")] RoleViewModel roleModel)
        {
            if (ModelState.IsValid)
            {
                var role = await RoleManager.FindByIdAsync(roleModel.Id);
                role.Name = roleModel.Name;
                await RoleManager.UpdateAsync(role);
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        //
        // POST: /Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id, string deleteUser)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var role = await RoleManager.FindByIdAsync(id);
                if (role == null)
                {
                    return HttpNotFound();
                }
                IdentityResult result;
                if (deleteUser != null)
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                else
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

DRCTS/Views/DRC/Analyst_Report.cshtml
@{
    ViewBag.Title = "Analyst Report";
}



<div class="row">
    <div class="col-md-10">
        <div class="panel panel-primary">
            <div class="panel-heading">
               <h1>Disability Resource Center - Reasonable Accommodation Report</h1> 
            </div>
            <div class="panel-body">
                <p>
                    On this page you can view a report of reasonable accommodations by analyst. Also you can filter this data by fiscal year and quarter.
                </p>
            </div>
            <!--<div class="panel-footer">
                Panel Footer
            </div>-->
        </div>
    </div>
</div>
<hr />
<br />

<div class="container col-md-12">
    <div class="form-group row">
        <div class="col-md-4">
            @Html.Label("Fiscal Year", htmlAttributes: new { @class = "control-label" })
            @Html.DropDownList("Fiscal_Year", ViewBag.dSource as SelectList, "Select One", new { htmlAttributes = new { @class = "form-control" } })

        </div>
        <div class="col-md-5">
            @Html.Label("Quarter", htmlAttributes: new { @class = "control-label" })
            @Html.DropDownList("Quarter", ViewBag.dSource2 as SelectList, "Select One", new { htmlAttributes = new { @class = "form-control" } })

        </div>
       <!-- <div class="col-md-2">
            <button type="button" class="btn btn-info btn-sm" id="all" onclick="saveFile()" data-toggle="modal" data-target="#cost"><i class="fa fa-file-excel-o"></i> Export Full Report</button>
        </div>-->

    </div>
    <br /><br />
    <div class="row">
        <div class="col-lg-11 col-md-11">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-title pull-left"><h2 style="font-size:125%">
    <i class="fa fa-table"></i> Number of Reasonable Accommodation By Analyst</h2>
</div>
                    <div class="panel-title pull-right"><button type="button" onclick="saveAnalystReport()" class="btn btn-info btn-sm" data-toggle="modal" id="service" data-target="#cost"><i class="fa fa-file-excel-o"></i> Export section</button></div>
                    <div class="clearfix"></div>
                </div>
                <div id="container1" style="overflow-x:auto">
                    @Html.Action("RAbyUser", "DRC", new { year = ViewBag.fyyear })
                </div>


                <div class="panel-footer">

                </div>
            </div>
        </div>


       
    </div>
    <a href="@Url.Action("Index", "DRC")"><i class="fa fa-home fa-fw"></i> Back to Home</a>
    </div>
    @section tables {

        <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
        <style>
            table {
                border-collapse: collapse;
            }

            table, td, th {
                border: 1px solid black;
            }

            th {
                background-color: #42444e;
                color: white;
            }
        </style>

        <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.js"> </script>
        <script type="text/javascript">
 $(document).ready(function () {
        $('.MyTable').DataTable();
    }); </script>

        <script type="text/javascript">
    function updateReport(year) {
        $.get("RAbyUser?year=" + year, function (data) {
            $('#container1').html(data);
        });
        $.get("Disability_Report?year=" + year, function (data) {
            $('#container2').html(data);
        });
        $.get("Status_Report?year=" + year, function (data) {
            $('#container3').html(data);
        });
        $.get("MD715Report?year=" + year, function (data) {
            $('#container4').html(data);
        });
    };



    $(function () {
        $('#Fiscal_Year').on("change", function () {
            var year = $(this).val();
            
            if ($("#Quarter option:selected").val() != 0) {
                year = year + "-" + $("#Quarter option:selected").val();
            }
            //alert(year + "-" + $("#Quarter option:selected").val());
            //alert(year);
            updateReport(year);


        });
        $('#Quarter').on("change", function () {
            var year = $("#Fiscal_Year option:selected").val();
            if ($("#Quarter option:selected").val() != 0) {
                year = year + "-" + $("#Quarter option:selected").val();
            }

           // alert(year);
            updateReport(year);


        });






    });

   
    function saveAnalystReport() {



        var table = $("#AnalystReport").tableToJSON();

        //alert("Fiscal_Year");
        var data1 = table;

        var today = new Date();
        var date = today.getFullYear() + '-' + (today.getMonth() + 1) + '-' + today.getDate();
        var opts = [{ sheetid: 'Analyst Report', header: true }];
        var res = alasql('SELECT INTO XLSX("AnalystReportFY' + $("#Fiscal_Year option:selected").val() + "-QT" + $("#Quarter option:selected").val() + "-" + date + '.xlsx",?) FROM ?',
                         [opts, [data1]]);
    }

   
        </script>

    }

DRCTS/Views/DRC/CustomColumns.cshtml
@model IEnumerable<DRCTS.Models.CheckModel>

<fieldset>
    <legend>Items already checked are visable by default</legend>
    <table class="table">


        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.CheckBoxFor(modelItem => item.Checked, new { @class = "toggle-vis", @data_column = item.Id, @id = Html.DisplayFor(modelItem => item.Id) })
                </td>
                <td>
                    @Html.Label(@Html.DisplayFor(modelItem => item.Name).ToString(), new { @for = Html.DisplayFor(modelItem => item.Id) })
                </td>


            </tr>
        }

    </table>
</fieldset>

DRCTS/Views/DRC/Index1.cshtml
@{
    ViewBag.Title = "Index1";
    Layout = "~/Views/DRC/_LayoutPageDRC2.cshtml";
}

<h2>Index1</h2>

DRCTS/Views/DRC/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
}

<h2>Request Not Found</h2>

DRCTS/Views/DRC/RAbyUser.cshtml
@model IEnumerable<DRCTS.Models.RAAnylistResult>
@{
    var total = Model.Sum(a => a.Total);
    var tNew = Model.Sum(a => a.New);
   
    var tOpen = Model.Sum(a => a.Open);
    
    var tOther = Model.Sum(a => a.Other);
   
    var tFull = Model.Sum(a => a.Fulfilled);
   
}
<style>
    table {
        border-collapse: collapse;
    }

    table, td, th {
        border: 1px solid black;
    }

    .tfo {
        font-weight: bolder;
        color: black;
        font: bold;
    }

    .spider {
        background-color: lightblue;
        color: black;
        font: bold;
    }
</style>
<table class="table" id="AnalystReport">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.New)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Open)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Other)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fulfilled)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th>Percentage</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.New)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Open)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Other)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fulfilled)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total)
            </td>
            <td>
                @{
                    var percentComplete = (decimal)(100 * item.Total) / (total == 0 ? total + 1 : total);
                    /* if (total > 0)
                     {
                         percentComplete = (decimal)(100 * item.Total) / total;
                     }*/

                    @percentComplete.Value.ToString("0.00")
                }
            </td>
        </tr>
    }
    <tfoot>
        <tr class="tfo">
            <td>Total</td>
            <td>@tNew</td>
            <td>@tOpen</td>
            <td>@tOther</td>
            <td>@tFull</td>
            <td>@total</td>
            </tr>
        </tfoot>
</table>

DRCTS/Views/DRC/_LayoutPageDRC1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DRC Tracking System</title>
    
    
   @Styles.Render("~/Content/fontawesome")
       @Styles.Render("~/Content/Swatch-SP")
        @Styles.Render("~/Content/startmin")
    @Styles.Render("~/Content/metis") 
   
    @Styles.Render("~/Content/calendar")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/textarea.css" rel="stylesheet" />
    <link href="~/Content/docs.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               <!-- @Html.ActionLink("DRC Tracking System", "Index", "DRC", null, new { @class = "navbar-brand" }) -->
                <a aria-hidden="true" id="home-page-logo_desktop" href="/" title="Home" rel="home" id="logo"><img src="~/img/logo.png" alt="US Department of Transportation" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   <!-- <li><i class="fa fa-home"></i>@Html.ActionLink("Home", "Index", "DRC")</li>
                    <li><i class="fa fa-file"></i>@Html.ActionLink("DRC Form", "AddRequest", "DRC")</li>
                    <li><i class="fa fa-file-excel-o"></i>@Html.ActionLink("DRC Reports", "Contact", "DRC")</li> -->
                    @if (Request.IsAuthenticated)
                    {

                    <li><a href="@Url.Action("Index", "DRC")"><i class="fa fa-home fa-fw"></i> Home</a></li>
                    <li>
                        <a href="@Url.Action("AddRequest", "DRC")"><i class="fa fa-edit fa-fw"></i> Form</a>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-table fa-fw"></i> Reports</a>
                        <ul class="dropdown-menu dropdown-user">
                          <!--  <li>
                                @Html.ActionLink("Test Report 1", "ReportTest", "DRC")
                            </li>-->
                            <li>
                                @Html.ActionLink("Test Report 1", "SummaryReport", "DRC")
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                        if (Request.IsAuthenticated && User.IsInRole("DRCAdmin"))
                        {
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-sun-o fa-fw"></i>Administration</a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                @Html.ActionLink("Roles", "Index", "RolesAdmin")
                            </li>
                            <li>
                                @Html.ActionLink("Users", "Index", "UsersAdmin")
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                        }
                    }
 </ul>
                <div class="row">
                    
                <div class="input-group custom-search-form">
                  @if (Request.IsAuthenticated)
                  {  <input type="text" class="form-control" placeholder="Search for Request...">
                    <span class="input-group-btn">
                        <button class="btn btn-primary" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                  }
                    @Html.Partial("_LoginPartial3")
                </div>
                    
                    </div>
                    
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - DOT Dept. Of Civil Rights</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/metis")
    @Scripts.Render("~/bundles/startmin")
    @Scripts.Render("~/bundles/calendar")
    @if (Request.IsAuthenticated)
    {
        <script type="text/javascript">
        var global_sess_expirationSeconds = @Session.Timeout*60;
        var global_sess_warningSeconds = @System.Configuration.ConfigurationManager.AppSettings["SessionWarningDelaySecond"].ToString();
        var global_LogoutUrl = "javascript:document.getElementById('logoutForm').submit()";
        var global_sess_resetPage = '@Url.Action("Index", "JS")';
        </script>
    }
    <script src="~/Scripts/session.warning.js"></script>
    @RenderSection("scripts", required: false)
    @RenderSection("crip", required: false)
    @RenderSection("tables", required: false)
</body>
</html>